# Generated by Django 3.0.5 on 2020-04-10 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 10, 8, 42, 22, 647531))),
                ('judul', models.CharField(max_length=500)),
                ('gambar', models.FileField(upload_to='')),
                ('konten', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_artikel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserNetijen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_user', models.CharField(max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserWartawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_user', models.CharField(max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_like', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 10, 8, 42, 22, 649613))),
                ('like_artikel', models.IntegerField(default=0)),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_espn.Artikel')),
                ('netizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_espn.UserNetijen')),
            ],
        ),
        migrations.CreateModel(
            name='Komen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_komen', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 10, 8, 42, 22, 648134))),
                ('komen', models.TextField()),
                ('artikel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_espn.Artikel')),
                ('netizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_espn.UserNetijen')),
            ],
        ),
        migrations.AddField(
            model_name='artikel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_espn.UserWartawan'),
        ),
        migrations.AddField(
            model_name='artikel',
            name='kategori_artikel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_espn.Kategori'),
        ),
    ]
